temp = {

    ':':       {'tName':'', 
                                        'm2m_o_s':['S|'],
                                        'm2m_i_s':['S|'],
                                        'm2m_a':['S|','S|'],
                                        'm2m_n':['S|','S|','S|','S|','S|'],
                                        'symmetry':"LR"},


}

muscles = {
    
    'thigh:quadratus lumborum':       {'tName':'quadratus lumborum', 
                                        'm2m_o_s':['S|pelvis:coxal'],
                                        'm2m_i_s':['S|vertebral:XII'],
                                        'm2m_a':['S|lumbales','S|ramus lumbalis'],
                                        'm2m_n':['S|subcostalis','S|lumbales1','S|lumbales2','S|lumbales3','S|lumbales4'],
                                        'symmetry':"LR"},
    'thigh:psoas minor':              {'tName':'psoas minor', 
                                        'presence':50,
                                        'm2m_o_s':['S|pelvis:coxal'],
                                        'm2m_i_s':['C|spinal:thoracic-vertebra12','C|spinal:lumbar-vertebra1'],
                                        'm2m_n':['S|lumbar plexus'],
                                        'm2m_delay_ant':['S|gluteus maximus'],
                                        'symmetry':"LR"},
    'thigh:gluteus maximus':          {'tName':'gluteus maximus', 
                                        'm2m_o_s':['C|sacral:1'],
                                        'm2m_i_s':['S|leg:femur'],
                                        'm2m_a':['S|superior gluteal','S|inferior gluteal'],
                                        'm2m_n':['S|inferior gluteal',],
                                        'm2m_delay_ant':['S|psoas minor','S|psoas major','S|iliacus'],
                                        'symmetry':"LR"},
    'thigh:gracilis':                 {'tName':'gracilis', 
                                        'm2m_o_s':['S|pelvis:coxal'],
                                        'm2m_i_s':['S|leg:tibia'],
                                        'm2m_a':['S|medial circumflex femoral'],
                                        'm2m_n':['S|anterior obturator'],
                                        'symmetry':"LR"},
    'thigh:iliacus':                  {'tName':'iliacus', 
                                        'm2m_o_s':['S|pelvis:ilium'],
                                        'm2m_i_s':['S|leg:femur'],
                                        'm2m_a':['S|medial femoral circumflex','S|iliolumbar'],
                                        'm2m_n':['S|femoral'],
                                        'm2m_delay_ant':['S|gluteus maximus'],
                                        'symmetry':"LR"},
    'thigh:psoas major':              {'tName':'psoas major', 
                                        'm2m_o_s':['C|spinal:thoracic-vertebra12','C|spinal:lumbar-vertebra1','C|spinal:lumbar-vertebra2',
                                                   'C|spinal:lumbar-vertebra3','C|spinal:lumbar-vertebra4','C|spinal:lumbar-vertebra5'],
                                        'm2m_i_s':['S|leg:femur'],
                                        'm2m_a':['S|iliolumbar','S|'],
                                        'm2m_n':['S|lumbar plexus'],
                                        'm2m_delay_ant':['S|gluteus maximus','S|gluteus medius'],
                                        'symmetry':"LR"},
    'thigh:pectineus':                {'tName':'pectineus', 
                                        'm2m_o_s':['S|pelvis:coxal'],
                                        'm2m_i_s':['S|femur'],
                                        'm2m_a':['S|obturator'],
                                        'm2m_n':['S|femural','S|obturator'],
                                        'symmetry':"LR"},
    'thigh:sartorius':                {'tName':'sartorius', 
                                        'm2m_o_s':['S|pelvis:coxal'],
                                        'm2m_i_s':['S|leg:tibia'],
                                        'm2m_a':['S|femoral'],
                                        'm2m_n':['S|femoral'],
                                        'symmetry':"LR"},
    'thigh:tensor fasciae latae':     {'tName':'tensor fasciae latae', 
                                        'm2m_o_s':['S|pelvis:ilium'],
                                        'm2m_i_s':['S|leg:femur'],
                                        'm2m_a':['S|lateral circumflex femoral','S|superior gluteal '],
                                        'm2m_n':['S|superior gluteal'],
                                        'symmetry':"LR"},
    'thigh:rectus femoris':           {'tName':'rectus femoris', 
                                        'm2m_o_s':['S|pelvis:ilium'],
                                        'm2m_i_s':['S|leg:patella'],
                                        'm2m_a':['S|lateral femoral circumflex'],
                                        'm2m_n':['S|femoral'],
                                        'm2m_delay_ant':['S|hamstring'],
                                        'symmetry':"LR"},
    'thigh:vastus lateralis':         {'tName':'vastus lateralis', 
                                        'm2m_o_s':['S|leg:femur'],
                                        'm2m_i_s':['S|leg:patella'],
                                        'm2m_a':['S|femoral'],
                                        'm2m_n':['S|femoral'],
                                        'm2m_delay_ant':['S|hamstring'],
                                        'symmetry':"LR"},
    'thigh:vastus medialis   ':       {'tName':'vastus medialis', 
                                        'm2m_o_s':['S|femur'],
                                        'm2m_i_s':['S|patella'],
                                        'm2m_a':['S|femoral'],
                                        'm2m_n':['S|femoral'],
                                        'symmetry':"LR"},
    'thigh:adductor longus':          {'tName':'adductor longus', 
                                        'm2m_o_s':['S|pelvic:pubis'],
                                        'm2m_i_s':['S|femur'],
                                        'm2m_a':['S|obturator'],
                                        'm2m_n':['S|anterior obturator'],
                                        'symmetry':"LR"},
    'thigh:adductor magnus':          {'tName':'adductor magnus', 
                                        'm2m_o_s':['S|pelvic:pubis','S|pelvic:ishium'],
                                        'm2m_i_s':['S|femur'],
                                        'm2m_a':['S|obturator'],
                                        'm2m_n':['S|anterior obturator','S|sciatic'],
                                        'symmetry':"LR"},
    'thigh:adductor brevis':          {'tName':'adductor brevis', 
                                        'm2m_o_s':['S|pelvic:pubis'],
                                        'm2m_i_s':['S|femur'],
                                        'm2m_a':['S|obturator'],
                                        'm2m_n':['S|obturator'],
                                        'symmetry':"LR"},
    'thigh:piriformis':               {'tName':'piriformis', 
                                        'm2m_o_s':['S|sacral:2','S|sacral:3','S|sacral:4',],
                                        'm2m_i_s':['S|femur'],
                                        'm2m_a':['S|inferior gluteal','S|lateral sacral','S|superior gluteal'],
                                        'm2m_n':['S|sacral2','S|lumbar5','S|sacral1'],
                                        'symmetry':"LR"},
    'thigh:gluteus medius':           {'tName':'gluteus medius',
                                        'm2m_o_s':['S|pelvic:ilium'],
                                        'm2m_i_s':['S|leg:femur'],
                                        'm2m_a':['S|superior gluteal'],
                                        'm2m_n':['S|lumbar4','S|lumbar5','S|sacral1'],
                                        'symmetry':"LR"},
}





connectives = {}

attachments = {}